version: "2"

run:
  timeout: 5m
  skip-dirs:
    - internal/mocks

linters:
  enable:
    - bodyclose
    - gocritic
    - gosec
    - makezero
    - misspell
    - nakedret
    - revive
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
  settings:
    staticcheck:
      checks:
        - "all"
        - -QF1008
        - -ST1000
